### ISSUE TITLE
Swap "Override" and "Append" options

### ISSUE THREAD

**Issue by vsudakov** [hasit/vscode-gi#1]
Hi, currently we have this list of options:

1. Override existing .gitignore
2. Append to gitignore

These two items should be swapped, because "Append" is used more often. So list should be:

1. Append to gitignore
2. Override existing .gitignore

Thank you.

**Comment by hasit** [comment]
@vsudakov 

You are right. Thank you for bringing that to notice. I will be more than happy to receive a PR from you with this change. If not, I will change it soon (in ~2 days).

**Comment by vsudakov** [comment]
@hasit I'm sorry, unfortunately I'm too busy these days...

**Comment by hasit** [comment]
@vsudakov 

No problem. I will make the change and reference this issue. Thank you once again.

**Comment by hasit** [comment]
Closing since I merged the PR with the changes
